// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wy6Yr1LdpLUQ7Fjg84jOj3IPQj9dFy8',
    appId: '1:39675466679:web:b7895099941cb4c1004e32',
    messagingSenderId: '39675466679',
    projectId: 'ogo-apps',
    authDomain: 'ogo-apps.firebaseapp.com',
    storageBucket: 'ogo-apps.appspot.com',
    measurementId: 'G-3QGTZFVZKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLEpE-yj8MhPw3_tiIKfA1BIo04bx1M4',
    appId: '1:39675466679:android:53cf1d5ba10c6bea004e32',
    messagingSenderId: '39675466679',
    projectId: 'ogo-apps',
    storageBucket: 'ogo-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3MbmaOyL2G-iZCr9BJhW-XyABeRpoOZQ',
    appId: '1:39675466679:ios:d8e2237aad2aa027004e32',
    messagingSenderId: '39675466679',
    projectId: 'ogo-apps',
    storageBucket: 'ogo-apps.appspot.com',
    iosClientId: '39675466679-idmp9a0ft74re7g4acmbrhrmmr2t19tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3MbmaOyL2G-iZCr9BJhW-XyABeRpoOZQ',
    appId: '1:39675466679:ios:d8e2237aad2aa027004e32',
    messagingSenderId: '39675466679',
    projectId: 'ogo-apps',
    storageBucket: 'ogo-apps.appspot.com',
    iosClientId: '39675466679-idmp9a0ft74re7g4acmbrhrmmr2t19tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelgo',
  );
}
